SRC = HumanA.cpp \
HumanB.cpp \
Weapon.cpp \
main.cpp
GPP = c++ -std=c++98
GFLAGS = -Wall -Wextra -Werror
RM = rm -f
Humans = Humans
all :
	$(GPP) $(GFLAGS) $(SRC) -o $(Humans)
fclean :
	$(RM) $(Humans)
