SRC = megaphone.cpp
OBJ = megaphone.opp
GPP = c++ -std=c++98
GFLAGS = -Wall -Wextra -Werror
RM = rm -f
MEGAPHONE = megaphone
all :
	$(GPP) $(GFLAGS) $(SRC) -o $(MEGAPHONE)
fclean :
	$(RM) $(MEGAPHONE)
