SRC = PhoneBook.cpp Contact.cpp main.cpp
GPP = c++ -std=c++98
GFLAGS = -Wall -Wextra -Werror
RM = rm -rf
PHONEBOOK = phonebook
all :
	$(GPP)  $(SRC) -o $(PHONEBOOK)
fclean :
	$(RM) $(PHONEBOOK)
re : fclean all