SRC = Zombie.cpp main.cpp newZombie.cpp randomChump.cpp
GPP = c++ -std=c++98
GFLAGS = -Wall -Wextra -Werror
RM = rm -f
Zombie = zombie
all :
	$(GPP) $(GFLAGS) $(SRC) -o $(Zombie)
fclean :
	$(RM) $(Zombie)
